<?php

namespace AppBundle\Repository;

/**
 * CompteReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteReservationRepository extends \Doctrine\ORM\EntityRepository
{
}
