<?php

namespace AppBundle\Repository;

/**
 * PayumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayumRepository extends \Doctrine\ORM\EntityRepository
{
}
