<?php

namespace AppBundle\Repository;

/**
 * ReservationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDateFull()
    {
        $query = $this->createQueryBuilder('r');

        $query->select('r.dateReservation')
            ->innerJoin('r.billets', 'b')
            ->having('COUNT(b.id) > 2')
            ->orderBy('r.dateReservation', 'ASC')
            ->groupBy('r.dateReservation');

        return $query->getQuery()->getArrayResult()g;
    }
}
