# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
   pdf_path: "%kernel.root_dir%/../web/uploads/pdf"

services:
   reservation.capture.event_subscriber:
       class: AppBundle\EventListener\ReservationSubscriber
       calls:
        - [ setSnappy, ["@knp_snappy.pdf"]]
        - [ setTwig, ['@twig']]
        - [ setPdfPath, ['%pdf_path%']]
        - [ setMailer, ['@mailer']]
       tags:
         - { name: kernel.event_subscriber }

   reservation.persist.event_subscriber:
      class: AppBundle\EventListener\ReservationSubscriber
      tags:
        - { name: kernel.event_subscriber }

   validator.date_reservation:
      class: AppBundle\Validator\Constraints\FullDateReservationValidator
      calls:
        - [ setEntityManager,['@doctrine.orm.entity_manager']]
      tags:
        - { name: validator.constraint_validator }

   validator.reservation:
      class: AppBundle\Validator\Constraints\ReservationValidator
      calls:
        - [ setEntityManager, ['@doctrine.orm.entity_manager']]
      tags:
        - { name: validator.constraint_validator}