# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
   pdf_path: "%kernel.root_dir%/../web/uploads/pdf"

services:
   reservation.capture.event_subscriber:
       class: AppBundle\EventListener\ReservationSubscriber
       arguments: ['@knp_snappy.pdf', '@twig', '%pdf_path%', '@mailer' ]
       tags:
         - { name: kernel.event_subscriber }

   calcul_prix.calcul_prix:
       class: AppBundle\CalculPrix\CalculPrix

   validator.date_reservation:
      class: AppBundle\Validator\Constraints\FullDateReservationValidator
      calls:
        - [ setEntityManager,['@doctrine.orm.entity_manager']]
      tags:
        - { name: validator.constraint_validator }

   validator.reservation:
      class: AppBundle\Validator\Constraints\ReservationValidator
      calls:
        - [ setEntityManager, ['@doctrine.orm.entity_manager']]
      tags:
        - { name: validator.constraint_validator }

   payment.stripe:
      class: AppBundle\Payment\StripePayment
      arguments: [ "%secret_key%", '@doctrine.orm.entity_manager', '@event_dispatcher']