# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
   pdf_path: "%kernel.root_dir%/../web/uploads/pdf/"

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        tags: ['controller.service_argument']

    AppBundle\Payment\StripePayment:
        arguments:
            $stripeKey: '%secret_key%'

    AppBundle\EventListener\PaymentListener:
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: processingPayment}

    AppBundle\Generator\GeneratorPDF:
        arguments:
            $pdfPath: '%pdf_path%'


