# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
   pdf_path: %kernel.root_dir%/../web/uploads/pdf

services:
   reservation.capture.event_subscriber:
       class: AppBundle\EventListener\ReservationSubscriber
       arguments: ["@knp_snappy.pdf", "@twig", "%pdf_path%", "@mailer"]
       tags:
         - { name: kernel.event_subscriber, method: generatePDF }
         - { name: kernel.event_subscriber, method: sendMail }

services:
  reservation.persist.event_subscriber:
      class: AppBundle\EventListener\ReservationSubscriber
      tags:
        - { name: kernel.event_subscriber, method: comptePrix}

services:
  validator.date_reservation:
    class: AppBundle\Validator\Constraints\FullDateReservationValidator
    calls:
      - [ setEntityManager,['@doctrine.orm.default_entity_manager']]
    tags:
      - { name: validator.constraint_validator }
