app_home:
    path: /
    defaults: { _controller: "AppBundle:App:index"}

app_tarifs:
    path: /tarifs_horaires
    defaults: { _controller: "AppBundle:App:tarifs"}

app_reservation:
    path: /reservation
    defaults: { _controller: "AppBundle:App:reservation"}

app_confirmation:
    path: /confirmation/{id}
    defaults: { _controller: "AppBundle:App:confirmation"}
    requirements:
      id: \d+

app_done:
    path: /done/{id}
    defaults: { _controller: "AppBundle:App:done"}
    requirements:
      id: \d+

app_billets:
    path:  /billeterie/{codeReservation}
    defaults: { _controller: "AppBundle:Billeterie:reservation"}
